http:
  routers:
    grafana:
      rule: "Host(`grafana.yapserver.fr`)"
      entrypoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - internal-only@file
        - authentik@file
      service: grafana-svc
      priority: 10

    # Route le handshake/callback de l'outpost vers Authentik (obligatoire en single-app)
    grafana-outpost:
      rule: "Host(`grafana.yapserver.fr`) && PathPrefix(`/outpost.goauthentik.io/`)"
      entrypoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: authentik-outpost-svc
      priority: 20

    prometheus:
      rule: "Host(`prometheus.yapserver.fr`)"
      entrypoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - internal-only@file
      service: prometheus-svc

  services:
    grafana-svc:
      loadBalancer:
        servers:
          - url: "http://10.0.30.11:3000"

    prometheus-svc:
      loadBalancer:
        servers:
          - url: "http://10.0.30.11:9090"

    authentik-outpost-svc:
      loadBalancer:
        servers:
          - url: "http://authentik-server:9000"
