http:
  routers:
    navidrome:
      rule: "Host(`music.yapserver.fr`)"
      entrypoints: [websecure]
      tls: {certResolver: cloudflare}
      middlewares: [internal-only@file, authentik@file]
      service: navidrome-svc
      priority: 10

    # Callback/handshake de l'outpost Authentik (obligatoire en forward_single)
    navidrome-outpost:
      rule: "Host(`music.yapserver.fr`) && PathPrefix(`/outpost.goauthentik.io/`)"
      entrypoints: [websecure]
      tls: {certResolver: cloudflare}
      service: authentik-outpost-svc
      priority: 20

  services:
    navidrome-svc:
      loadBalancer:
        servers:
          - url: "http://10.0.30.13:4533"
