http:
  routers:
    splitpro:
      rule: "Host(`split.yapserver.fr`)"
      entrypoints: [websecure]
      tls: {certResolver: cloudflare}
      middlewares: [internal-only@file]
      service: splitpro-svc

  services:
    splitpro-svc:
      loadBalancer:
        servers:
          - url: "http://10.0.30.12:3002"
