http:
  routers:
    wazuh:
      rule: "Host(`wazuh.yapserver.fr`)"
      entrypoints: [websecure]
      tls: {certResolver: cloudflare}
      middlewares: [internal-only@file]
      service: wazuh-svc
  services:
    wazuh-svc:
      loadBalancer:
        serversTransport: wazuh-insecure
        servers:
          - url: "https://10.0.30.14:443"
  serversTransports:
    wazuh-insecure:
      insecureSkipVerify: true

