services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.11
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.yapserver.fr
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/jellyfin:/media:ro
    ports:
      - "8096:8096"
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
    name: traefik-proxy
