services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.10
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.yapserver.fr
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/jellyfin:/media:ro
      - type: bind
        source: /mnt/films
        target: /mnt/films
        read_only: true
        bind:
          propagation: rslave
    ports:
      - "8096:8096"
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
    name: traefik-proxy
